#!/bin/bash
set -eo pipefail
source ./bt.cfg
function cleanLibtest () {
  rm -f lib_test
}
function cleanLibauklet () {
  rm -f rt.o libauklet.a libauklet.tgz
}
case "$1" in
  clean)
    cleanLibtest
    cleanLibauklet
    ;;
  test)
    echo 'bt: running unit tests...'
    cleanLibtest
    ${CC} -o lib_test ${CFLAGS} -g -lpthread lib_test.c lib.c
    ./lib_test
    ;;
  lib)
    echo 'bt: compiling libauklet...'
    cleanLibauklet
    ${CC} -o rt.o -c ${CFLAGS} -DAUKLET_VERSION="\"$(cat VERSION)\"" -DAUKLET_TIMESTAMP="\"${TIMESTAMP}\"" rt.c
    ${AR} rcs libauklet.a rt.o
    ;;
  libinstall)
    ./$0 lib
    echo 'bt: installing libauklet...'
    sudo cp libauklet.a ${INSTALL}/libauklet.a
    ;;
  libuninstall)
    echo 'bt: uninstalling libauklet...'
    sudo rm -f ${INSTALL}/libauklet.a
    ;;
  libpkg)
    ./$0 lib
    echo 'bt: packaging libauklet...'
    tar cz -f ${TARNAME} libauklet.a
    ;;
  *)
    echo 'Usage: $0 [ clean | test | lib | libinstall | libuninstall | libpkg ]'
    exit 1
    ;;
esac
echo 'bt: done.'
