version: '2'

volumes:
  producer_pipcache: {}

services:
 auklet:
    build:
      context: .
      dockerfile: ./compose/auklet/Dockerfile
    command: /startAuklet.sh
    env_file: .env
    volumes:
      - .:/app
