version: '2'

services:
  auklet:
    build:
      context: .
      dockerfile: ./compose/auklet/Dockerfile
    env_file: .env
    volumes:
      - .:/go/src/github.com/user/myProject/app

  release:
    build:
      context: .
      dockerfile: ./compose/auklet/Dockerfile
    env_file: .env
    volumes:
      - .:/go/src/github.com/user/myProject/app
