version: '2'

services:
  wrapper:
    build:
      context: .
      dockerfile: ./compose/auklet/Dockerfile
    command: /runWrapper.sh
    env_file: .env
    volumes:
      - .:/go/src/github.com/user/myProject/app

  release:
    build:
      context: .
      dockerfile: ./compose/auklet/Dockerfile
    command: /makeRelease.sh
    env_file: .env
    volumes:
      - .:/go/src/github.com/user/myProject/app
